# common params
camera_name: 'Astra_Pro_Plus'
depth_registration: false
enable_point_cloud: false
enable_colored_point_cloud: false

# color params
enable_color: true
color_width: 640
color_height: 480
color_fps: 30
color_format: "MJPG"
enable_color_auto_exposure: false
color_exposure: 50 # 5ms
color_gain: -1 # -1 default

# depth params
depth_width: 640
depth_height: 480
depth_fps: 30
depth_format: "Y11"

# ir exposure
enable_ir_auto_exposure: false
ir_exposure: 5000 # 5ms
ir_gain: 40

enable_ir: true
ir_width: 640
ir_height: 480
ir_fps: 30
ir_format: "Y10"
