# Configuration file for the "joy_teleop" node inside "joystick_teleop.launch.py" 
# This node receive joystick input and convert to a TwistStamped message

x1_joy:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped  # Type of message that the node publishes
      topic_name: x1_controller/cmd_vel        # Topic over which the node publishes the message

      deadman_buttons: [6]                            # The deadman button needs to be pressed when sending velocity command (button [5] is the LR button on PS4)
      axis_mappings: 
        twist-linear-x:
          axis: 1          # Vertical axis of left joystick on a PS4 controller
          scale: 1.0
          offset: 0.0

        twist-angular-z:
          axis: 2
          scale: 1.0
          offset: 0.0